# Generated by Django 3.0.3 on 2020-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_chinadayaddlist_chinadaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeadRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubeiRate', models.CharField(max_length=20)),
                ('notHubeiRate', models.CharField(max_length=20)),
                ('countryRate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyHealRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubeiRate', models.CharField(max_length=20)),
                ('notHubeiRate', models.CharField(max_length=20)),
                ('countryRate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNewAddHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubei', models.IntegerField()),
                ('country', models.IntegerField()),
                ('notHubei', models.IntegerField()),
            ],
        ),
    ]
