# Generated by Django 3.0.3 on 2020-02-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_dailydeadratehistory_dailyhealratehistory_dailynewaddhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('confirm', models.IntegerField()),
                ('totalConfirm', models.IntegerField()),
                ('totalSuspect', models.IntegerField()),
                ('totalDead', models.IntegerField()),
                ('totalHeal', models.IntegerField()),
                ('deadRate', models.CharField(max_length=20)),
                ('healRate', models.CharField(max_length=20)),
                ('parent', models.CharField(default='', max_length=20)),
                ('child', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
