# Generated by Django 3.0.3 on 2020-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_areatree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatree',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
