# Generated by Django 3.0.3 on 2020-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200217_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('nowSevere', models.IntegerField()),
                ('nowConfirm', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
