# Generated by Django 3.0.3 on 2020-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_dailyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('url', models.URLField()),
                ('media', models.CharField(max_length=50)),
                ('cmsId', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=20)),
                ('publish_time', models.CharField(max_length=20)),
                ('can_use', models.IntegerField()),
            ],
        ),
    ]
