# Generated by Django 3.0.3 on 2020-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_articlelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WuhanDayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmAdd', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
