# Generated by Django 3.0.3 on 2020-02-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_wuhandaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSSList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('hash', models.IntegerField()),
                ('cur_path', models.FilePathField()),
                ('oss_path', models.FilePathField()),
                ('bucket', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
