# Generated by Django 3.0.3 on 2020-03-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_osslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaadd',
            name='importedCase',
            field=models.IntegerField(default=0),
        ),
    ]
