# Generated by Django 3.0.3 on 2020-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('confirm', models.IntegerField()),
                ('totalConfirm', models.IntegerField()),
                ('totalSuspect', models.IntegerField()),
                ('totalDead', models.IntegerField()),
                ('totalHeal', models.IntegerField()),
                ('deadRate', models.CharField(max_length=20)),
                ('healRate', models.CharField(max_length=20)),
                ('parent', models.CharField(default='', max_length=20)),
                ('type', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('url', models.URLField()),
                ('media', models.CharField(max_length=50)),
                ('cmsId', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=20)),
                ('publish_time', models.CharField(max_length=20)),
                ('can_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChinaAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('nowSevere', models.IntegerField()),
                ('nowConfirm', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChinaDayAddList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('deadRate', models.CharField(max_length=20)),
                ('healRate', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChinaDayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.IntegerField()),
                ('suspect', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('nowConfirm', models.IntegerField()),
                ('nowSevere', models.IntegerField()),
                ('deadRate', models.CharField(max_length=20)),
                ('healRate', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyDeadRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubeiRate', models.CharField(max_length=20)),
                ('notHubeiRate', models.CharField(max_length=20)),
                ('countryRate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyHealRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubeiRate', models.CharField(max_length=20)),
                ('notHubeiRate', models.CharField(max_length=20)),
                ('countryRate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heal', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('nowConfirm', models.IntegerField()),
                ('healRate', models.CharField(max_length=10)),
                ('deadRate', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyNewAddHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hubei', models.IntegerField()),
                ('country', models.IntegerField()),
                ('notHubei', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WuhanDayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmAdd', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
